---
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  before_script: []
  script:
    - gem install rubocop --no-ri --no-rdoc
    - rubocop

# rspec:
#   script:
#   - rspec spec

pages:
  stage: deploy
  before_script: []
  script:
    - gem install yard
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master
