---
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor

rubocop:
  before_script: []
  script:
    - gem install rubocop --no-ri --no-rdoc
    - rubocop lib

test:
  script:
  - gem install ci_reporter_test_unit mocha test-unit --no-ri --no-rdoc
  - GENERATE_REPORTS=true CI_REPORTS=reports rake test
  artifacts:
    reports:
      junit: "reports/TEST-*.xml"

pages:
  stage: deploy
  before_script: []
  script:
    - gem install yard
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master
