---
image: "ruby:2.6"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

rubocop:
  script:
    - gem install rubocop -N
    - rubocop lib

test:
  before_script:
    - sed -e 's/# gem /gem /' -i Gemfile
    - gem install bundler -N
    - bundle install -j $(nproc) --path vendor
  coverage: '/\((\d+.\d+\%)\) covered/'
  script:
    - GENERATE_REPORTS=true CI_REPORTS=reports bundle exec rake test
  artifacts:
    expire_in: 1 week
    paths:
      - coverage/
    reports:
      junit: "reports/TEST-*.xml"

pages:
  stage: deploy
  script:
    - gem install yard -N
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master
  when: always
