---
image: "ruby:2.4"

# Cache gems in between builds
cache:
  paths:
    - vendor/ruby

before_script:
  - gem install bundler -N
  - bundle install -j $(nproc) --path vendor

rubocop:
  before_script: []
  script:
    - gem install rubocop -N
    - rubocop lib

test:
  script:
    - GENERATE_REPORTS=true CI_REPORTS=reports bundle exec rake test
  artifacts:
    reports:
      junit: "reports/TEST-*.xml"

pages:
  stage: deploy
  before_script: []
  script:
    - gem install yard -N
    - yard doc -o public/
  artifacts:
    paths:
      - public/
  only:
    - master
  when: always
